/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application     //includes java plugin
    jacoco          //ADDED
}
repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}
dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")
    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

//ADDED ----------------------------------------------------
    // https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    //JSON
    // https://mvnrepository.com/artifact/org.json/json
    implementation("org.json:json:20201115" )
}
application {
    // Define the main class for the application.
    mainClass.set("it.unibo.wenvusage.MoveVirtualRobot")     //CHANGED
    //mainClass.set("it.unibo.wenvusage.App")                //ORIGINAL
}